version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crudtoalgo_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Opção A (recomendada para MVP): usar Judge0 público via API (menor esforço, menos risco)
  # Opção B: rodar um executor local (apenas se souber isolar/sandbox)
  # judge0:
  #   image: judge0/api:latest
  #   ports:
  #     - "2358:2358"
  #   environment:
  #     - JUDGE0_DB=somevalue

volumes:
  pgdata:
